app/src/styles/blocks/_loading.scss
app/src/styles/mortar.scss
app/src/styles/typography/_textcolors.scss

https://jira.nationalgeographic.com/browse/SYTO-258
**Testing Instructions**:
1. checkout branch
- grunt serve
- visit http://localhost:3000/blocks.html#loadingAnimation

add loading spinner and text

---

app/src/styles/_base.scss

https://jira.nationalgeographic.com/browse/AEM-3353
Hey I'm Ben Pearson the new Front End Dev @CSE. We have a recommendation from @asabaylus to change this at the Mortar level. Let us know you would rather we override it with AEM.

[AEM-3353] Remove text selection color

---

app/site/layouts/default.html
app/site/patterns/index.html
app/styles/_main.scss
app/styles/layout/columns.html
app/styles/patterns/_buttons.scss
app/styles/theme/_fonts.scss

https://jira.nationalgeographic.com/browse/MORTAR-30
Testing instructions: 
1. git checkout
2. gulp serve
3. Visit http://localhost:3000/patterns

Mortar-30 Buttons

---

.eslintrc
app/modules/modals/scripts.js
app/scripts/main.js
gulp/tasks/test.js
package.json

- checkout branch
- `npm install`
- `gulp test`
- verify that there are no errors

add eslint task and rules

---

app/src/styles/elements/_btn.scss

https://jira.nationalgeographic.com/browse/MORTAR-1
Testing instructions:
- checkout branch
- `npm install`
- 'npm install grunt-cli -g'
- `grunt serve`
-  open [http://localhost:3000/elements.html]()

remove y-axis difference on button state change

---

app/src/styles/_base.scss

Change per Kevin's comments in: https://jira.nationalgeographic.com/browse/AEM-3353

[AEM-3353] remove text-shadow: none from selection

---

app/site/_layouts/default.html
app/site/components/figure.html
app/site/components/index.html

https://jira.nationalgeographic.com/browse/MORTAR-51
- `gulp serve`
- browse to [http://localhost:3000/components]()
- verify that the example exists and matches the specifications

add figure example

---

app/styles/theme/transactions.html
app/styles/themes/default/vars/_colors.scss

https://jira.nationalgeographic.com/browse/MORTAR-65
- look at the code
- make sure the value is updated correctly

update youtube color value

---

app/site/components/figure.html
app/styles/_shame.scss

https://jira.nationalgeographic.com/browse/MORTAR-51
git checkout 
run `gulp serve`
browse to http://localhost:3000/components
verify that the example exists and matches the specifications

fix margin between caption and source

---

app/site/patterns/index.html
app/styles/_main.scss
app/styles/elements/_links.scss
app/styles/elements/links.html

https://jira.nationalgeographic.com/browse/MORTAR-66
Instructions 
-git checkout 
-gulp serve 
-visit localhost:3000/patterns

Add links documentation

---

app/styles/_main.scss
app/styles/global/functions/_shade.scss
app/styles/global/functions/_tint.scss
app/styles/global/vars/_theme.scss
app/styles/mortar-default.scss
app/styles/themes/default/vars/_colors.scss

https://jira.nationalgeographic.com/browse/MORTAR-46
- verify that values have been updated

change danger and affirmation values

---

app/site/layout/index.html
app/styles/layout/column-gutters.html
app/styles/layout/columns.html
app/styles/layout/columnsdoc.html
app/styles/layout/rows.html

https://jira.nationalgeographic.com/browse/MORTAR-88
Testing instructions
-Git checkout
-Gulp serve 
-Visit http://localhost:3000/layout/ and verify that language has been updated

Update language on layout page

---

app/modules/modals/doc.html
app/styles/blocks/counters.html
app/styles/blocks/videopromo.html

https://jira.nationalgeographic.com/browse/MORTAR-87
- Git checkout 
- gulp serve
- Visit http://localhost:3000/patterns and verify that language's been updated

Update language on UI Page

---

app/site/colors/index.html

https://jira.nationalgeographic.com/browse/MORTAR-97
Instructions: 
- git checkout
- gulp serve
- Visit http://localhost:3000/colors to see updated intro text

Mortar-97 Update intro text on color page

---

app/styles/layout/column-gutters.html
app/styles/layout/columns.html
app/styles/layout/columnsdoc.html
app/styles/layout/rows.html

https://jira.nationalgeographic.com/browse/MORTAR-118
Instructions: 
-Git checkout
-gulp serve
-http://localhost:3000/layout

Cleanup: Update language on Layout page

---

app/site/_styles/docs.scss

https://jira.nationalgeographic.com/browse/MORTAR-109
Instructions: 
git checkout
gulp serve
visit http://localhost:3000/ to see nav update

Cleanup: Change nav colors

---

app/styles/layout/rows.html

https://jira.nationalgeographic.com/browse/MORTAR-112
git checkout
gulp serve
visit http://localhost:3000/layout/

Add zero-row gutter example

---

app/styles/elements/buttons.html

https://jira.nationalgeographic.com/browse/MORTAR-117
git checkout 
gulp serve
http://localhost:3000/patterns

Update text on UI page

---

app/styles/theme/pragmatica.html

https://jira.nationalgeographic.com/browse/MORTAR-115
Instructions:
-Git checkout
-gulp serve
-http://localhost:3000/typography

Cleanup: remove color for .mt_subh3

---

app/styles/layout/rows.html

https://jira.nationalgeographic.com/browse/MORTAR-121
git checkout 
gulp serve
http://localhost:3000/layout/

Cleanup: Remove 2nd column of row example

---

app/styles/elements/inputs.html

https://jira.nationalgeographic.com/browse/MORTAR-114
git checkout 
gulp serve
http://localhost:3000/patterns

Feature/mortar 114 - Checkbox and radio text updates

---

app/site/_layouts/default.html

https://jira.nationalgeographic.com/browse/MORTAR-116
Instructions:
-Git checkout
-gulp serve
-Check for text color update at http://localhost:3000

Cleanup: Change text elements color in <body> to gray

---

app/site/components/index.html

https://jira.nationalgeographic.com/browse/MORTAR-119
git checkout
gulp serve
http://localhost:3000/components

Cleanup: Update language on component page

---

app/styles/theme/_blockquotes.scss

https://jira.nationalgeographic.com/browse/MORTAR-113
Instructions:
-Git checkout
-gulp serve
-http://localhost:3000/typography

Cleanup: change blockquote size

---

app/icons/_icon-examples.html
app/icons/_icons.html
app/icons/_styles.scss
app/site/_styles/docs.scss
app/site/icons/index.html

https://jira.nationalgeographic.com/browse/MORTAR-93
- `gulp serve`
- view the icons documentation page
- verify that the examples exist and are to specification

add icon and label patterns

---

app/site/_partials/home/links.html

https://jira.nationalgeographic.com/browse/MORTAR-137
- git checkout 
- gulp serve
- visit http://localhost:3000 and look for updated text in "Other useful links" section

Style manual link

---

app/styles/themes/default/vars/_typography.scss

https://jira.nationalgeographic.com/browse/MORTAR-123
-git checkout 
-gulp serve
-Verify font-size update http://localhost:3000/typography

Cleanup: change font size of .mt_h2

---

app/styles/themes/default/vars/_typography.scss

https://jira.nationalgeographic.com/browse/MORTAR-133
-git checkout 
-check css for fallback fonts

Add fallback fonts

---

app/styles/themes/default/vars/_typography.scss

Check typography.scss for Nimbus sans L

Add Nimbus sans l

---

app/scripts/main.js
app/scripts/pestle/lib/module.js
app/scripts/pestle/main.js
gulp/tasks/karma.js
gulp/tasks/test.js
karma.conf.js
package.json
test/app/scripts/pestle/lib/module_test.js
test/app/scripts/pestle/pestle_test.js

https://jira.nationalgeographic.com/browse/MORTAR-151
- git checkout feature/mortar-151
- gulp karma

Create Pestle.js in Mortar repo

---

app/site/_layouts/default.html
app/site/_styles/docs.scss
app/site/components/figure.html
app/styles/layout/column-gutters.html
app/styles/layout/columnsdoc.html
app/styles/layout/rows.html

https://jira.nationalgeographic.com/browse/MORTAR-166
-git checkout 
-gulp serve 
-Look for code snippets on component page http://localhost:3000/components

Add code snippets to photo captions

---

app/site/icons/index.html

https://jira.nationalgeographic.com/browse/MORTAR-162
- `gulp serve`
- browse to icon page
- make sure the icon documentation makes sense

add icon documentation

---

app/site/_partials/home/philosophy.html
app/site/index.html

https://jira.nationalgeographic.com/browse/MORTAR-161
-git checkout
-gulp serve
-http://localhost:3000/

Add design philosophy to frontpage

---

app/site/_styles/docs.scss
app/site/color/index.html
app/styles/theme/colordoc.html
app/styles/theme/neutrals.html
app/styles/theme/primary.html
app/styles/theme/socialbrands.html
app/styles/theme/transactions.html

https://jira.nationalgeographic.com/browse/MORTAR-171
-git checkout
-gulp serve
-http://localhost:3000/color

Update color doc

---

app/site/_partials/home/links.html

Update favicon documentation on homepage
https://jira.nationalgeographic.com/browse/MORTAR-168
- git checkout
- gulp serve
- http://localhost:3000/

Finish favicon documentation

---

app/site/_styles/docs.scss
app/styles/blocks/_partials/dotcounter-snippets.html
app/styles/blocks/_partials/videopromo-snippets.html
app/styles/components/figure.html

New PR 
https://jira.nationalgeographic.com/browse/MORTAR-172
Check components and patterns pages for superfluous code in snippets

rm superfluous classes from snippets -Components & Patterns

---

app/site/_layouts/default.html

https://jira.nationalgeographic.com/browse/MORTAR-196
- git checkout
- gulp serve
- Look for favicon on every page

Add favicon

---

app/styles/components/_relatedcontent.scss
app/styles/components/relatedcontent.html

https://jira.nationalgeographic.com/browse/MORTAR-186
git checkout
gulp serve
http://localhost:3000/components

Related content links

---

app/site/_layouts/default.html
app/site/_styles/docs.scss

https://jira.nationalgeographic.com/browse/MORTAR-191
- git checkout
- gulp serve
- Verify that code snippets wrap on mobile

Make snippets wrap on mobile

---

app/site/_partials/home/links.html

Update favicon link
- git checkout
- gulp serve

Update favicon link

---

app/icons/_icons.html
app/site/_styles/docs.scss
app/site/icons/index.html

https://jira.nationalgeographic.com/browse/MORTAR-197
git checkout
gulp serve
http://localhost:3000/icons

Update icons Page

---

app/styles/patterns/_select.scss

https://jira.nationalgeographic.com/browse/MORTAR-204
git checkout
gulp test 
Make sure tests pass

alphabetize properties

---

app/styles/patterns/_select.scss

https://jira.nationalgeographic.com/browse/MORTAR-197
git checkout
gulp serve
Visit http://localhost:3000/icons and download the icons. Opening the zip file should open a folder named 'natgeo-icons"

Update icon zip file

---

app/styles/components/ratios.html
app/styles/components/relatedcontent.html

https://jira.nationalgeographic.com/browse/MORTAR-205
-git checkout
-gulp serve
-http://localhost:3000/components

Add snippets to components page

---

app/modules/slider/docs.html
app/modules/slider/scripts/MTSlider.jsx
app/modules/slider/scripts/MTSliderPestle.js
app/site/_layouts/default.html
gulp/tasks/scripts.js
gulp/tasks/serve.js
package.json

https://jira.nationalgeographic.com/browse/MORTAR-182
* `gulp serve`
* view code to make sure the react-slide component is being properly included and used
* view documentation (http://localhost:3000/components/) to ensure the content fromt he markup is being passed to the slider

add react-slick slider to MT slider

---

app/scripts/pestle/README.md
app/scripts/pestle/examples/example1/Component.jsx
app/scripts/pestle/examples/example1/MyModule.js
app/scripts/pestle/examples/example1/index.html
app/scripts/pestle/examples/example1/main.js
app/scripts/pestle/examples/example2/Component.jsx
app/scripts/pestle/examples/example2/MyModule.js
app/scripts/pestle/examples/example2/index.html
app/scripts/pestle/examples/example2/main.js
app/scripts/pestle/examples/example3/Component.jsx
app/scripts/pestle/examples/example3/MyModule.js
app/scripts/pestle/examples/example3/index.html
app/scripts/pestle/examples/example3/main.js
app/scripts/pestle/examples/example4/Component.jsx
app/scripts/pestle/examples/example4/MyModule.js
app/scripts/pestle/examples/example4/index.html
app/scripts/pestle/examples/example4/main.js
app/scripts/pestle/examples/index.html
gulp/tasks/examples.js
package.json

This PR adds documentation for Pestle and some basic examples.
To test:
- `npm install` (only the first time)
- `gulp runExamples`

[MORTAR-160] Document Component Development Pattern

---

app/scripts/pestle/main.js
package.json

To test:
- `gulp serve`
- Go to "Components" menu
- Open the javascript console
- Write a suscriber:
```
Pestle.PubSub.suscribe('hello', function() {
console.log('Hello World!');
});
```
- Then publish
```
Pestle.PubSub.publish('hello');
```

[MORTAR-200] research and define a pub/sub pattern for events

---

app/modules/slider/scripts/MTSlider.jsx
karma.conf.js
test/app/modules/slider/slider_test.js

[MORTAR-182] Fixing broken build

---

app/styles/_main.scss
app/styles/blocks/_partials/videopromo-snippets.html
app/styles/blocks/videopromo.html
app/styles/components/ratios.html
app/styles/utils/_circle.scss
app/styles/utils/_intratios.scss
app/styles/utils/_round.scss

https://jira.nationalgeographic.com/browse/MORTAR-206
git checkout
gulp serve
`.mt_round` is removed from code and replaced by `.mt_intratio--circle`

Create mt_intratio--circle class

---

app/icons/_icon-examples.html

https://jira.nationalgeographic.com/browse/MORTAR-213
git checkout
gulp serve 
http://localhost:3000/icons

Add code snippets to icon w/ label section

---

app/modules/slider/_styles.scss
app/modules/slider/docs.html
app/modules/slider/scripts/MTSlider.jsx
app/modules/slider/scripts/MTSliderPestle.js
karma.conf.js
package.json
test/app/modules/slider/slider_test.js

https://jira.nationalgeographic.com/browse/MORTAR-180
* check that looping and non-looping galleries work as expected
* check that inactive button state shows up when expected

add ability to toggle looping/infinte feature, inactive slider button state

---

app/styles/theme/article.html

https://jira.nationalgeographic.com/browse/MORTAR-202
Git checkout
gulp serve 
http://localhost:3000/typography

Fix html character bug

---

app/modules/slider/docs.html

https://jira.nationalgeographic.com/browse/MORTAR-184
* view the docs
* ask yourself whether you know how to implement a slider or not

add slider documentation

---

app/modules/modals/doc.html
app/site/icons/index.html
app/site/typography/index.html
app/styles/patterns/_buttons.scss
app/styles/patterns/_partials/buttons-snippets.html
app/styles/patterns/buttons.html

https://jira.nationalgeographic.com/browse/MORTAR-208
- Git checkout
- gulp serve 
- Check code for updated button classnames. Make sure nothing breaks on the site

Update button classnames

---

app/modules/button/_styles.scss
app/modules/button/docs.html
app/modules/button/scripts/CTAButton.jsx
app/modules/button/scripts/CTAButtonPestle.js
app/modules/icon/docs.html
test/app/modules/button/button_test.js
test/app/modules/icon/icon_test.js

https://jira.nationalgeographic.com/browse/AEM-5423
Of note: There are many errors showing up when running tests. These seem unrelated to these tests as I confirmed they are showing up on master. Seems related to Pestle, but I did not have time to investigate further. Also, I fixed a bug I discovered in testing in which not all styles were being applied correctly for some conditions.

[test/AEM-5423] Create React Unit Test - CTA Button (including Icon Component) and Documentation

---

app/icons/_icon-snippets.html
app/site/_styles/docs.scss
app/site/icons/index.html
app/styles/patterns/_partials/buttons-snippets.html
app/styles/patterns/buttons.html

https://jira.nationalgeographic.com/browse/MORTAR-238
git checkout
gulp serve
http://localhost:3000/icons/ - click on a radio button to see updated icon snippets 
http://localhost:3000/patterns/ - click on a radio button to see updated button snippets

Refresh code snippets on toggle

---

app/icons/_icon-examples.html
app/modules/button/docs.html
app/modules/icon/docs.html
app/modules/modals/doc.html
app/modules/slider/docs.html
app/site/_layouts/default.html
app/site/_styles/docs.scss
app/styles/blocks/_partials/dotcounter-inverse-snippets.html
app/styles/blocks/_partials/dotcounter-snippets.html
app/styles/blocks/_partials/numericcounter-disabled-snippets.html
app/styles/blocks/_partials/numericcounter-snippets.html
app/styles/blocks/_partials/videopromo-snippets.html
app/styles/components/figure.html
app/styles/components/relatedcontent.html
app/styles/layout/columnsdoc.html
app/styles/layout/rows.html
app/styles/patterns/_partials/buttons-snippets.html
app/styles/patterns/_partials/input-snippets.html
app/styles/theme/article.html

https://jira.nationalgeographic.com/browse/MORTAR-207
Verify that expand button is added to long code snippets.
Test every page on http://localhost:3000/

Add expand button to code snippets

---

app/scripts/pestle/examples/example6/.babelrc
app/scripts/pestle/examples/example6/components/todo/TodoPestle.js
app/scripts/pestle/examples/example6/components/todo/actions/index.js
app/scripts/pestle/examples/example6/components/todo/components/AddTodoForm.js
app/scripts/pestle/examples/example6/components/todo/components/Footer.js
app/scripts/pestle/examples/example6/components/todo/components/Link.js
app/scripts/pestle/examples/example6/components/todo/components/Todo.js
app/scripts/pestle/examples/example6/components/todo/components/TodoItem.js
app/scripts/pestle/examples/example6/components/todo/components/TodoList.js
app/scripts/pestle/examples/example6/components/todo/containers/AddTodo.js
app/scripts/pestle/examples/example6/components/todo/containers/FilterLink.js
app/scripts/pestle/examples/example6/components/todo/containers/TodoForm.js
app/scripts/pestle/examples/example6/components/todo/containers/VisibleTodoList.js
app/scripts/pestle/examples/example6/components/todo/reducers/index.js
app/scripts/pestle/examples/example6/components/todo/reducers/todos.js
app/scripts/pestle/examples/example6/components/todo/reducers/visibilityFilter.js
app/scripts/pestle/examples/example6/components/todo/selectors/index.js
app/scripts/pestle/examples/example6/components/todoStatistics/TodoStatisticsPestle.js
app/scripts/pestle/examples/example6/components/todoStatistics/components/Counter.js
app/scripts/pestle/examples/example6/components/todoStatistics/components/Statistics.js
app/scripts/pestle/examples/example6/components/todoStatistics/containers/StatisticsDisplay.js
app/scripts/pestle/examples/example6/components/todoStatistics/reducers/index.js
app/scripts/pestle/examples/example6/index.html
app/scripts/pestle/examples/example6/main.js
app/scripts/pestle/examples/example6/package.json
app/scripts/pestle/examples/example6/server.js
app/scripts/pestle/examples/example6/webpack.config.js
app/scripts/pestle/examples/index.html

To test:
- Go to `app/scripts/pestle/example/example6`
- Run `npm install` then `npm start`

[MORTAR-159] Pestle-Redux example

---

app/modules/sharing/docs.html

https://jira.nationalgeographic.com/browse/MORTAR-226
* check copy on components page

add social sharing documentation

---

app/styles/layout/columnsdoc.html
app/styles/theme/article.html

https://jira.nationalgeographic.com/browse/MORTAR-207
This update fixes the attached issue.

Typography page - Add .codesnippet-wrapper to appropriate div

---

app/modules/slider/scripts/MTSlider.jsx
test/app/modules/button/button_test.js
test/app/modules/icon/icon_test.js
test/app/modules/slider/slider_test.js

https://jira.nationalgeographic.com/browse/MORTAR-258
* pull branch
* run `gulp karma`
* see that the output is much cleaner

get rid of React console errors, false positives in unit tests

---

.sass-lint.yml
app/modules/button/_styles.scss
app/modules/sharing/_styles.scss
app/modules/slider/_styles.scss
app/styles/_reset.scss
app/styles/layout/_rows.scss
package.json

https://jira.nationalgeographic.com/browse/MORTAR-260
* pull branch
* run `gulp sasslint`
* observe that output is smaller than it was

fix linting warnings

---

app/modules/button/scripts/CTAButton.jsx
app/modules/photogallery/_styles.scss
app/modules/photogallery/docs.html
app/modules/photogallery/scripts/MTPhotoGallery.jsx

This request simply provides more examples in the documentation for QA to verify functionality. Also, I squashed a bug in the button component that appeared when the class names changed.

[feature/SYTO-633-2] Improve documentation examples for QA, button component bug fix

---

app/modules/tooltips/_styles.scss
app/modules/tooltips/scripts/MTTooltip.jsx

https://jira.nationalgeographic.com/browse/SYTO-665
This update includes the following events:  Click, mouseEnter & mouseLeave
Instructions: 
Click to display. Click to hide. 
Hover to display. Navigate to hide
- git checkout branch
- gulp serve
- http://localhost:3000/components

Tooltip hover

---

app/modules/promocard/docs.html
app/modules/promocard/scripts/MTPromoCard.jsx
app/modules/promocard/scripts/PromoImage.jsx
test/app/modules/promocard/promocard_test.js

https://jira.nationalgeographic.com/browse/AEM-5627

[test/AEM-5627] Create React Unit Test & Documentation - Promo Component

---

app/site/index.html

https://jira.nationalgeographic.com/browse/MORTAR-242
Instructions: 
- git checkout branch
- gulp serve
- Visit homepage. 
- Verify that the documentation for the css & font is accurate.

Update doc for mortar usage

---

app/modules/promocard/_styles.scss
app/modules/promocard/components/shared/PromoImage.jsx
app/modules/promocard/components/shared/PromoText.jsx
app/modules/promocard/components/types/Article.jsx
app/modules/promocard/configurator/MTPromoCardConfigurator.jsx
app/modules/promocard/configurator/MTPromoCardConfiguratorPestle.js
app/modules/promocard/docs.html
app/modules/promocard/scripts/MTPromoCard.jsx
app/modules/promocard/scripts/MTPromoCardPestle.js
test/app/modules/promocard/article_test.js
test/app/modules/promocard/promocard_test.js

https://jira.natgeo.com/browse/SYTO-756
To test:
pull branch
```
gulp serve
```
Component configuration can be tested at: http://192.168.108.154.xip.io:3000/components/promo

[feature/SYTO-756] Create article variation of story card

---

app/site/_layouts/default.html
app/styles/theme/_pullquotes.scss
app/styles/theme/pullquotes.html
app/styles/themes/default/vars/_typography.scss

https://jira.natgeo.com/browse/SYTO-741
- git checkout branch
- gulp serve
- Look for updated pull quote style here http://localhost:3000/typography/

[SYTO-741] Update pull quote style

---

app/styles/themes/default/vars/_typography.scss

Reverts natgeo/mortar#206
Sorry. This change was meant to be done for release/3.0
Reverting and creating new PR.

Revert "Feature/SYTO-742 Remove Chronicle & Pragmatica from Mortar 3 "

---

app/site/_layouts/default.html
app/styles/theme/_pullquotes.scss
app/styles/theme/pullquotes.html

Reverts natgeo/mortar#210
Sorry. This change was meant to be done for release/3.0
Reverting and creating new PR.

Revert "[SYTO-741] Update pull quote style"

---

app/styles/theme/socialbrands.html
app/styles/themes/default/vars/_colors.scss

https://jira.natgeo.com/browse/SYTO-792
On the color page, check the console to confirm the google + color update as specified in the AC

[SYTO-792] Update google + color

---

app/modules/modals/_styles.scss

https://jira.natgeo.com/browse/SYTO-883
1. ``gulp serve``
2. Open http://localhost:3000/patterns/
3. Go to Modal section and click on the button
4. Check the modal changes.

[SYTO-883] Restyle Modal (Mortar)

---

app/styles/theme/_links.scss

https://jira.natgeo.com/browse/SYTO-768
Confirm that hyperlink styles have been updated to match the design.

[SYTO-768]Update hyperlink styles

---

src/modules/promocard/components/shared/PromoImage.js
src/modules/promocard/components/types/Story.js
src/modules/promocard/configurator/MTPromoCardConfigurator.js
src/modules/promocard/configurator/MTPromoCardConfiguratorPestle.js
src/modules/promocard/docs.html

To test:
- gulp serve
- Verify first Promo Card on component menu is using cropping srcsets.

[SYTO-893] FE: Handle manual crops in promo cards

---

src/styles/layout/column-gutters.html
src/styles/layout/columns.html

https://jira.natgeo.com/browse/SYTO-912
Instructions:
On the layout page, look for copy updates and the new column gutter documentation specified in the AC.

[SYTO-912] Update column gutter documentation

---

src/modules/videoplaylist/VideoPlaylist.js
src/modules/videoplaylist/_styles.scss
src/modules/videoplaylist/docs.html
src/site/mockdata/videoplaylist/data.json

JIRA: https://jira.natgeo.com/browse/SYTO-879
----
- git checkout feature/SYTO-879
- gulp serve
- videoplaylist's thumbnails should be scroll-able only at desktop.
- it should have a black gradient at bottom.

[SYTO-879] - Update playlist to handle 5+ videos.

---

test/src/modules/video/video_test.js

Just check gulp test is working.

[SYTO-916] Fix test

---

src/contentPackages/configurator/CodeSnippet.js
src/contentPackages/configurator/Configurator.js
src/modules/podpromo/configurator/docs.html
src/site/_layouts/default.html
src/site/_styles/docs.scss

https://jira.natgeo.com/browse/SYTO-907
Updates: The code snippet is now a React component.
Instructions:
Confirm the expand button works as expected on http://localhost:3000/components/podpromo/index.html

[SYTO-907] Edit code snippet in the POD Configurator

---

src/contentPackages/heroWithTwoRails/docs.html
src/contentPackages/heroWithTwoRails/heroWithTwoRails.js
src/modules/promocard/MTPromoCard.js

https://jira.natgeo.com/browse/SYTO-932

[SYTO-932] Update MTPromoCard to call ShowCard when needed

---

package.json
src/modules/videoplaylist/VideoCaption.js

Reverts natgeo/mortar#327
- Not reviewed
- and failing in /components (dotdotdot issue)

Revert "[AEM-6013-2] import jquery into video captions component, bump version"

---

package.json

/lib folder gitignored but needed for npm

Bump for publishing built /lib in npm.

---

package.json
src/modules/videoplaylist/VideoCaption.js
src/modules/videoplaylist/VideoThumbnail.js
src/scripts/main.js

These are Mortar changes for implementation in AEM

[AEM-6013-3] changes for video playlist

---

src/contentPackages/contentpackage/configurator/docs.html
src/contentPackages/contentpackage/docs.html
src/contentPackages/heroWithTwoRails/configurator/docs.html
src/contentPackages/heroWithTwoRails/docs.html
src/modules/broadsheet/docs.html
src/modules/modals/doc.html
src/modules/photogallery/docs.html
src/modules/podpromo/configurator/docs.html
src/modules/podpromo/docs.html
src/modules/promocard/configurator/docs.html
src/modules/promocard/docs.html
src/modules/showcard/docs.html
src/modules/slider/docs.html
src/modules/tooltips/docs.html
src/modules/videomodal/docs.html
src/modules/videoplaylist/configurator/docs.html
src/modules/videoplaylist/docs.html
src/site/_styles/docs.scss
src/site/components/promo/index.html
src/site/contentPackages/index.html
src/site/index.html

```
$ git checkout SYTO-1073
$ gulp serve
```
check that some features got badged

[SYTO-1073] add badges to 'in development' features

---

src/modules/modals/_styles.scss
src/modules/videomodal/VideoModal.js
src/modules/videomodal/_styles.scss

https://jira.natgeo.com/browse/SYTO-978
1. ``gulp serve`` and ``gulp test``
2. Go to components and scroll down until the video promo component and then click it.
3. Check the AC is met.

[SYTO-978] Video Modal CSS stuff

---

npm-debug.log
package.json

Need a new version due to shameful NPM misunderstanding on my part

version 3.1.5 (no changes)

---

package.json

bump version to 3.1.6

---

src/contentPackages/contentpackage/components/FourUp.js
src/contentPackages/contentpackage/docs.html

https://jira.natgeo.com/browse/AEM-6728

[AEM-6728] Gallery issues in 4-Up

---

src/modules/podpromo/PodPromo.js
src/modules/podpromo/_styles.scss
src/modules/podpromo/configurator/MTPodPromoConfigurator.js
src/modules/podpromo/configurator/MTPodPromoConfiguratorPestle.js
src/modules/podpromo/docs.html
test/src/modules/podpromo/podpromo_test.js

https://jira.natgeo.com/browse/AEM-6380

[AEM-6380] POD Promo Image Afilliation does not render

---

src/modules/promocard/_styles.scss
src/styles/themes/default/vars/_z.scss

https://jira.natgeo.com/browse/AEM-6742
These are changes in Mortar based on the temporary fix from https://jira.natgeo.com/browse/AEM-6730

[AEM-6742] Long Term Fix for Not able to click on the title of the Story Card in the Hero position of the HTR

---

src/site/_styles/docs.scss

https://jira.natgeo.com/browse/SYTO-1230

Fix icon misalignment on tablet breakpoints

---

test/src/modules/button/button_test.js

https://jira.natgeo.com/browse/AEM-6795
Updates to the Button Unit Test in Mortar to account for different types

[AEM-6795] Button Unit Test improvement

---

src/site/_styles/docs.scss
src/site/components/index.html
src/styles/blocks/channelbranding.html

https://jira.natgeo.com/browse/SYTO-1181
Components are displayed in alphabetical order with the exception of content packages which are listed at the bottom.

[SYTO-1181] Alphabetize components

---

package.json

https://jira.natgeo.com/browse/AEM-6652

[AEM-6652-vb] Bump Mortar Version to 3.1.21

---

.sass-lint.yml
src/contentPackages/contentpackage/_styles.scss
src/modules/broadsheet/_styles.scss
src/modules/button/_styles.scss
src/modules/modals/_styles.scss
src/modules/photogallery/_styles.scss
src/modules/podpromo/_styles.scss
src/modules/promocard/_styles.scss
src/modules/showcard/_styles.scss
src/modules/video/_styles.scss
src/modules/videomodal/_styles.scss
src/modules/videoplaylist/_styles.scss
src/site/_styles/docs.scss
src/styles/_main.scss
src/styles/grid/_column-gutters.scss
src/styles/grid/_columns.scss
src/styles/themes/default/vars/_colors.scss
src/styles/themes/default/vars/_mqs.scss
src/styles/themes/default/vars/_typography-fontfaces.scss
src/styles/utils/_circle.scss
src/styles/utils/_richtext.scss

Fixed a lot of sasslint warnings.

---

test/src/contentPackages/contentPackage/components/fiveUpCard_test.js
test/src/contentPackages/contentPackage/components/fiveUp_test.js
test/src/contentPackages/contentPackage/components/testData.js

https://jira.natgeo.com/browse/AEM-6821
https://jira.natgeo.com/browse/AEM-6823
To Test:
- Pull AEM-6821+AEM-6823
- Run npm test
- Verify tests pass

[AEM-6821] [AEM-6823] Adding in test for five up card, adding checks for new props being passed to five up promo

---

test/src/contentPackages/contentPackage/contentPackage_test.js

https://jira.natgeo.com/browse/AEM-6820
To test:
Pull AEM-6820
Run npm test
Verify tests pass

[AEM-6820] Adding tests in for contentPackage container

---

test/src/modules/icon/icon_test.js

https://jira.natgeo.com/browse/AEM-6796

[AEM-6796] Update Icon Unit Test

---

README.md
package.json

bump to 3.1.22

---

src/site/components/index.html

https://jira.natgeo.com/browse/SYTO-1181
Reordered content packages like so: 
-Broadsheet
-Content Package
-Hero with Two Rails
-POD Promo
-Video Playlist

Reorder Content Packages

---

src/scripts/main.js
src/site/_layouts/default.html
src/site/_styles/docs.scss
src/site/nav/SecondaryNav.js
src/site/nav/SiteNav.js

https://jira.natgeo.com/browse/SYTO-1173
https://jira.natgeo.com/browse/SYTO-1174
Update: New Nav

[SYTO-1173][1174] Update Mortar site nav

---

test/src/modules/tooltips/MTToolTip_test.js

https://jira.natgeo.com/browse/AEM-6822
To test:
- Pull AEM-6822
- Run `npm test`
- verify tests pass

[AEM-6822] Adds in tests for tooltip component

---

README.md
package.json

bump versj to 3.1.23

---

src/site/icons/index.html
src/styles/patterns/buttons.html
src/styles/patterns/inputs.html

https://jira.natgeo.com/browse/SYTO-1175
Confirm the AC is met.

[SYTO-1175] Update background color on inverse

---

src/modules/broadsheet/MTBroadsheet.js
src/modules/broadsheet/MTBroadsheetPestle.js
src/modules/broadsheet/_styles.scss
src/modules/button/CTAButton.js

https://jira.natgeo.com/browse/AEM-6859
Adds in CTA button to Broadsheet
To test:
- Pull AEM-6859
- Run `gulp serve`
- Load the components page
- Check CTA button functionality and display at various breakpoints on broadsheet

[AEM-6859] Adds CTA button to Broadsheet

---

test/src/modules/videoplaylist/videoplaylist_test.js

Can't replicate the issue locally, so this is a bit of a shot in the dark...

skip video playlist test, to see if that fixes pipeline

---

src/modules/broadsheet/MTBroadsheet.js
src/modules/broadsheet/MTBroadsheetPestle.js
src/modules/broadsheet/_styles.scss
src/modules/broadsheet/docs.html

https://jira.natgeo.com/browse/AEM-6810
Changes include tweaks to text styling, updating data model and associated JS to pull in issue date (using the AEM data model as canon), updates so HTML renders properly in various fields 
To test:
- Pull AEM-6810
- gulp serve
- Verify layout.

[AEM-6810] Broadsheet Text Styling

---

test/src/modules/promocard/components/promoimage_test.js

https://jira.natgeo.com/browse/AEM-6801
Pull AEM-6801
run `npm test`
Verify tests pass with acceptable coverage.

[AEM-6801] Promo Card Unit Test
