natgeo/mortar

bower.json

https://jira.nationalgeographic.com/browse/AEM-4728
There's a story on the AEM sites to add the "whatsapp" icon to our "Follow Us" component. While looking into the story I found that we're a couple of versions behind on the latest released version of https://github.com/natgeo/icongs/releases
While attempting to update the version required on AEM sites I found that there's also a dependency in Mortar, which made my attempts to update AEM fail in the build process.
This change bumps the version of icongs to the latest release. I'm not clear on procedures needed to fully vet the change. I've done some quick smoke tests of the AEM sites with this updated version of the icon font set which appears to render fine.

[AEM-4728] Bumping icongs version to latest release 0.13.0

---

app/modules/slider/_styles.scss
package.json

To test:
- `npm install`
- `gulp serve`
- Go to slider component then click the slider and try to navigate using the keyboard arrows.

[MORTAR-188] Keyboard Navigation for Slider component 

---

app/styles/patterns/_partials/buttons-snippets.html
app/styles/patterns/buttons.html

https://jira.nationalgeographic.com/browse/MORTAR-241
git checkout
gul serve
Focus is removed from inactive buttons so you can no longer tab through. http://localhost:3000/patterns

Remove focus from inactive buttons 

---

packages/pestle/package.json

To test:
- On a temp folder run `npm install @natgeo/pestle`
- Go to `node_modules/@natgeo/pestle`
- Open `package.json` and verify version property is `2.1.0`

[AEM-5515] Renamed pestle to @natgeo/pestle on npm

---

app/site/_styles/docs.scss

https://jira.nationalgeographic.com/browse/MORTAR-207
Make sure expand button under code snippets shows up on small screens. *Only* applicable to code snippets with height > 240px

Fix expand button disappearance on small screens

---

app/modules/sharing/scripts/MTEmailButton.jsx

https://jira.nationalgeographic.com/browse/MORTAR-231
* click the email button in the sharing component
* make sure there are no unescaped HTML tags in the body of the email

remove html from email body

---

app/modules/photogallery/docs.html
app/modules/photogallery/scripts/MTPhotoGallery.jsx
app/modules/slider/scripts/MTSlider.jsx
app/modules/slider/scripts/imageSlide.jsx

No ticket associated with this. Refactor to ensure the srcset array is being passed to the ImageSlide for responsive images in the Slider for standalone and in a PhotoGallery.

[SYTO-633-imageFix] pass srcset to ImageSlide

---

app/modules/tooltips/_styles.scss
app/modules/tooltips/docs.html
app/modules/tooltips/scripts/MTTooltip.jsx

https://jira.nationalgeographic.com/browse/SYTO-698
-Instructions
- git checkout
- gulp serve
- Visit  http://localhost:3000/components
Look for the following: 
- Tooltip content now supports a max-width
- Hover area is limited to the button. The tooltip is activated when you hover over the button.

Apply max-width to tooltip

---

app/styles/themes/default/vars/_typography.scss

https://jira.natgeo.com/browse/SYTO-742
PR to merge into master but I can close this if it's needed in branch release 3.0 instead
Update: Chronicle & Pragmatica fonts are both removed from the codebase. 
Instructions: 
- git checkout branch 
- gulp serve
- Check the code.

Feature/SYTO-742 Remove Chronicle & Pragmatica from Mortar 3 

---

app/modules/slider/docs.html

Slider examples were using NG images that somehow got missing (removed, moved, whatever).
This PR makes use of placehold.it URLs that are less likely to change and serves the same as purpose is to test slider around.
Te check it:
- See Components section, Slider.
- You should see placeholdit images (colorful squares with size in pixels of the image being fetched).
- Have a beer, you deserve it for sure.

Replace NG missing images URLs for more stable placehold.it URLs.

---

app/modules/videoplaylist/_styles.scss
app/modules/videoplaylist/scripts/VideoCaption.jsx
app/modules/videoplaylist/scripts/VideoPlaylist.jsx

https://jira.natgeo.com/browse/SYTO-759
This PR gives a solution with the truncation of the text below the video component
I reccomend to use charles proxy in order to change this json http://www.nationalgeographic.com/versions/20160804-v1/_jcr_content/content/videoplaylist.promo-all.json and change the abstract property.
1. ``npm i``
2. ``gulp serve``
3. Go to components section
4. Scroll down until videplaylist
5. Check if the caption of the video has truncation when the text is very long.

[SYTO-759] Create truncate component for playerlist

---

app/site/_layouts/default.html
app/styles/themes/default/vars/_typography.scss

https://jira.natgeo.com/browse/SYTO-742
Chronicle and Pragmatica are restored to the CSS and removed from HTML as per AC.
Instruction:
- git checkout 
- gulp serve
- Inspect the console to verify the following no longer appear in the head tag:
`<link rel="stylesheet" href="https://fonts.ngeo.com/hoefler/1-0-1/hco_fonts.css">`
- You should no longer see this

[SYTO-742] Remove Chronicle & Pragmatica

---

app/contentPackages/contentpackage/docs.html

To test:
- Pull SYTO-822-2
- Run gulp serve
- Head over to http://localhost:3000/contentPackages/
- Confirm Configurator link takes you to http://localhost:3000/contentPackages/contentPackage/index.html

[SYTO-822] Fixes typo in link to configurator

---

app/modules/video/scripts/video.jsx
app/modules/videoplaylist/_styles.scss
app/modules/videoplaylist/scripts/VideoCaption.jsx
app/modules/videoplaylist/scripts/VideoPlaylist.jsx
app/modules/videoplaylist/scripts/VideoThumbnail.jsx
app/styles/themes/default/vars/_mqs.scss

This PR intends to apply miumum css changes in order to reskin thumbnail list for large and desktop breakpoints.
- git checkjout feature/SYTO-797
- gulp serve
Small Desk:
Large Desk:

Reskin VideoPlaylist Thumbnails Promos Desktop and Mobile

---

app/scripts/util/PortalComponentMixin.jsx
app/scripts/util/PortalWrapper.jsx
gulp/tasks/copy.js
gulp/tasks/paths.js
package.json

in the work for https://jira.natgeo.com/browse/AEM-5957, we identified a couple small changes needed in Mortar - 
1. react-element-query is only a devDependency - it should be a peerDependency
2. the contents of the app/scripts/util file should be available in /lib
3. small tweaks to the Portal components

[AEM-5957] Fix a few odds and ends related to using m3 components in AEM

---

package.json
src/modules/video/_styles.scss
src/styles/themes/default/vars/_colors.scss

https://jira.natgeo.com/browse/SYTO-867
This work pulls in the most recent update to modules-images: https://github.com/natgeo/modules-images, which has a new default placeholder color for images.
In addition, a placeholder was added to the video player that matches the new defaults in modules-images, per the ticket.
To test:
- npm i
- build
- confirm new placeholder color appears for images and video where appropriate

[SYTO-867] Change default placeholder color

---

src/modules/video/video.js

This PR intends to fix mortar videoplaylist when using latest modules-video (1.3.2).
You can test this only using the latest version modules video: blocker SYTO-1113
- git checkout bug/SYTO-1119
- gulp serve
- navigate to localhost:3000/components/
- scroll down to the videoplaylist, standing at there refresh the page.
- ensure the browser loads the page from that standing point and click on the videoplaylist items
- expected: the video should load.
---
JIRA: https://jira.natgeo.com/browse/SYTO-1119

[bug/SYTO-1119] - Video playlist sometimes does not change videos.

---

package.json
src/modules/broadsheet/MTBroadsheet.js
src/modules/broadsheet/MTBroadsheetPestle.js
src/modules/subscribecard/subscribeCard.js
src/styles/theme/_article.scss

https://jira.natgeo.com/browse/AEM-6812
This PR is needed to allow Broadsheet support for the AEM Smartbody functionality in author mode, in combination with an AEM PR: https://github.com/natgeo/aem-all/pull/1998
It also refactors the component to be more data-defensive - it previously broke if any of its data-model was not provided. 
This PR is not concerned with final styling for the Broadsheet elements in AEM - much is wonky and will be resolved later. 
To test: build, make sure Broadsheet still works, make sure tests pass

[AEM-6812] Broadsheet: AEM Smartbody support

---

src/contentPackages/contentpackage/components/FourUp.js

https://jira.natgeo.com/browse/AEM-6652
This may be tested in Mortar by deleting all cards except the first two, and in AEM (after copying /lib) any page that has a Content Package present such as http://aem.localhost.nationalgeographic.com:4502/content/ngdotcom/en_US/versions/v1.html,
which I believe should be present if the Homepage content package was installed previously.

[AEM-6652] 4-Up margin in first 2 promos prevents even rails when scrolling

---

src/contentPackages/contentpackage/components/FourUp.js

https://jira.natgeo.com/browse/AEM-6652
This is to fix a bug found in testing, where if the four-up only has the first card it does not align.

[AEM-6652v2] 4-Up margin in first 2 promos prevents even rails when scrolling

---

src/modules/videoplaylist/VideoCaption.js

Apparently there're a couple of errors being spitted from enzyme's `shallow` when tests finish.
This time bamboo's log says that:
```
>> http://bamboo.int.ngeo.com/download/MPPRJ-MN-MORT2UNT/build_logs/MPPRJ-MN-MORT2UNT-118.log
build	05-Dec-2016 17:54:52	PhantomJS 2.1.1 (Linux 0.0.0) ERROR
build	05-Dec-2016 17:54:52	  TypeError: undefined is not a function (evaluating '(0,_jquery2.default)(this.refs.abstract).css({height:'6em'}).dotdotdot')
build	05-Dec-2016 17:54:52	  at /tmp/b417f9448444231805651e2aa920f23b.browserify:96727 <- src/modules/videoplaylist/VideoCaption.js:9:0
```
so, now it checks for existence of element before calling `.css()`. Further cleanup and fixing is coming in future PR.
Thanks.

Quick fix for test.
